export const mockErrorUserAlreadyExists = {
  statusCode: 422,
  error: "User already exists.",
};

export const mockErrorInternalServer = {
  statusCode: 500,
  error: "Internal Server Error",
};

export const mockErrorEmailAlreadyExists = {
  statusCode: 422,
  error: "E-mail already in use.",
};

export const mockErrorUserNotFound = {
  statusCode: 400,
};
